version: '3.8'

services:
  form-filler:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: form-filler-local
    ports:
      - "${PORT:-3001}:3001"  # Map host port to container port 3001
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - NODE_ENV=development
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright/
      - TZ=${TZ:-UTC}
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # Enable debug logging in development
      - DEBUG=app:*,playwright:*,form-filler:*
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/uploads
      - /tmp/playwright:/tmp/playwright
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request('http://localhost:3000/health', {timeout: 5000}, (res) => {if (res.statusCode === 200) process.exit(0); else process.exit(1);}).on('error', () => process.exit(1)).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    stop_grace_period: 1m
    restart: unless-stopped
    # Enable hot-reload in development
    command: sh -c "npm install && npx playwright install && npm run dev"

networks:
  default:
    driver: bridge

volumes:
  uploads:
    driver: local
