version: '3.8'

services:
  form-filler:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: form-filler-local
    ports:
      - "${PORT}:${PORT}"  # Map host port to container port
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - NODE_ENV=${NODE_ENV}
      - PLAYWRIGHT_BROWSERS_PATH=${PLAYWRIGHT_BROWSERS_PATH}
      - TZ=${TZ}
      - LANG=${LANG}
      - LC_ALL=${LC_ALL}
      - DEBUG=${DEBUG}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/uploads
      - /tmp/playwright:/tmp/playwright
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request('http://localhost:${PORT}/health', {timeout: 5000}, (res) => {if (res.statusCode === 200) process.exit(0); else process.exit(1);}).on('error', () => process.exit(1)).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '${CONTAINER_CPUS}'
          memory: ${CONTAINER_MEMORY}
    stop_grace_period: 1m
    restart: unless-stopped
    # Enable hot-reload in development
    command: sh -c "npm install && npx playwright install && npm run dev"

networks:
  default:
    driver: bridge

volumes:
  uploads:
    driver: local
