# Dockerfile.playwright
FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /app

COPY package.json ./
RUN npm install

COPY playwright-service.js ./

EXPOSE 8080

CMD ["node", "playwright-service.js"]