# docker-compose.yml
version: '3.8'
services:
  form-automation:
    build: .
    ports:
      - "3008:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - redis
      - ollama
    volumes:
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots

#  ollama:
#    image: ollama/ollama:latest
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama_data:/root/.ollama
#    command: >
#      sh -c "ollama serve &
#             sleep 10 &&
#             ollama pull mistral:7b &&
#             ollama pull llava:7b &&
#             wait"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  playwright-service:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    ports:
      - "8088:8080"
    environment:
      - BROWSER_POOL_SIZE=5
    volumes:
      - ./screenshots:/app/screenshots

volumes:
  ollama_data:
  redis_data: